- url: 'https://github.com/ROBOTIS-GIT/turtlebot3/issues/427'
  title: '''''ImportError" during Follower Demo'
  body: "ISSUE TEMPLATE ver. 0.2.0\r\n\r\n1. Which TurtleBot3 you have?\r\n\r\n    - [x ] Burger\r\n    - [ ] Waffle\r\n    - [ ] Waffle Pi\r\n\r\n2. Which SBC(Single Board Computer) is working on TurtleBot3?\r\n\r\n    - [x ] Raspberry Pi 3\r\n    - [ ] Intel Joule 570x\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)\r\n\r\n3. Which OS you installed in SBC?\r\n\r\n    - [ ] Ubuntu MATE 16.04 or later\r\n    - [x ] Raspbian\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)\r\n\r\n4. Which OS you installed in Remote PC?\r\n\r\n    - [x ] Ubuntu 16.04 LTS (Xenial Xerus)\r\n    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)\r\n    - [ ] Linux Mint 18.x\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)\r\n\r\n5. Write down software version and firmware version\r\n\r\n    - Software version: Latest (downloaded 16/05/19)\r\n    - Firmware version: Latest (downloaded 16/05/19)\r\n \r\n6. Write down the commands you used in order\r\n\r\n    - PC : roscore\r\n    - Turtlebot : roslaunch turtlebot3_bringup turtlebot3_robot.launch\r\n    - PC : roslaunch turtlebot3_bringup turtlebot3_remote.launch\r\n    - PC : roslaunch turtlebot3_follow_filter turtlebot3_follow_filter.launch\r\n    - PC : roslaunch turtlebot3_follower turtlebot3_follower.launch\r\n \r\n7. Copy and Paste your error message on terminal\r\n\r\n    process[follower-1]: started with pid [4686]\r\n[INFO] [1558107315.566191]: Follower node initialized\r\nTraceback (most recent call last):\r\n  File \"/home/student/catkin_ws/src/turtlebot3_applications/turtlebot3_follower/nodes/follower\", line 137, in <module>\r\n    main()\r\n  File \"/home/student/catkin_ws/src/turtlebot3_applications/turtlebot3_follower/nodes/follower\", line 132, in main\r\n    follow = follower()\r\n  File \"/home/student/catkin_ws/src/turtlebot3_applications/turtlebot3_follower/nodes/follower\", line 31, in __init__\r\n    self.clf = pickle.load(open(self.config_dir + '/clf', \"rb\"))\r\n  File \"/usr/lib/python2.7/pickle.py\", line 1384, in load\r\n    return Unpickler(file).load()\r\n  File \"/usr/lib/python2.7/pickle.py\", line 864, in load\r\n    dispatch[key](self)\r\n  File \"/usr/lib/python2.7/pickle.py\", line 1096, in load_global\r\n    klass = self.find_class(module, name)\r\n  File \"/usr/lib/python2.7/pickle.py\", line 1130, in find_class\r\n    __import__(module)\r\nImportError: No module named sklearn.ensemble.forest\r\n[follower-1] process has died [pid 4686, exit code 1, cmd /home/student/catkin_ws/src/turtlebot3_applications/turtlebot3_follower/nodes/follower __name:=follower __log:=/home/student/.ros/log/2e06e492-78b9-11e9-b0bd-000c293d2fe3/follower-1.log].\r\nlog file: /home/student/.ros/log/2e06e492-78b9-11e9-b0bd-000c293d2fe3/follower-1*.log\r\nall processes on machine have died, roslaunch will exit\r\nshutting down processing monitor... Hi !\r\n... shutting down processing monitor complete\r\ndone\r\n  \r\n8. Please, describe detailedly what difficulty you are in \r\n\r\nHi !\r\nSorry for the inconvenience. I'm looking to execute the following demo, I've done all the steps including installing sklearn. After some research I have the impression that this module''sklearn.ensemble.forest'' no longer exists so I don't know what to do...\r\nThank you in advance for your help!\r\n\r\n"
  repo: 'https://api.github.com/repos/ROBOTIS-GIT/turtlebot3'
  labels:
    - in progress
- url: 'https://github.com/ROBOTIS-GIT/turtlebot3/issues/394'
  title: 'cmd_vel topic doesn''t exist '
  body: " **Issue: Follow the guide(http://emanual.robotis.com/docs/en/platform/turtlebot3/ros2/#ros2) to use turtlebot3 on ROS2, execute bringup steps, and check the ros2 topic list,  the result is that no cmd_vel topic exist. Not known something if I have missed. Does anyone met the same issue before, would you please share some experience about how to fix or debug? many thanks.**\r\n\r\nISSUE TEMPLATE ver. 0.2.0\r\n\r\n\r\n1. Which TurtleBot3 you have?\r\n\r\n    -  Waffle\r\n\r\n\r\n2. Which SBC(Single Board Computer) is working on TurtleBot3?\r\n\r\n\r\n    - Intel NUC6i\r\n\r\n\r\n3. Which OS you installed in SBC?\r\n\r\n    - Ubuntu 18.04\r\n\r\n4. Which OS you installed in Remote PC?\r\n\r\n\r\n5. Write down software version and firmware version\r\n\r\n    - Software version: [master]\r\n    - Firmware version: [1.0.1]\r\n \r\n6. Write down the commands you used in order\r\n\r\n    - HERE\r\n \r\n7. Copy and Paste your error message on terminal\r\n\r\n    - HERE\r\n  \r\n8. Please, describe detailedly what difficulty you are in \r\n\r\n\r\n\r\nBelow is execution steps:\r\n rapdev1@rapdev1:~/turtlebot3$ MicroXRCEAgent serial /dev/ttyACM0\r\nSerial agent initialization... OK\r\nEnter 'q' for exit\r\n\r\n\r\nrapdev1@rapdev1:~/turtlebot3$ MicroXRCEAgent udp 2018\r\nUDP agent initialization... OK\r\nEnter 'q' for exit\r\nRTPS Participant matched 1.f.59.e.c6.16.0.0.1.0.0.0|0.0.1.c1\r\nRTPS Participant matched 1.f.59.d.aa.7f.0.0.1.0.0.0|0.0.1.c1\r\n\r\nrapdev1@rapdev1:/data/proj/sdk/tb3_ws$ ~/turtlebot3/turtlebot3_lidar\r\nturtlebot3 lidar client setup complete!\r\n1 - Sent topic: 0.870000, range_max: 361\r\n2 - Sent topic: 0.871000, range_max: 361\r\n3 - Sent topic: 0.866000, range_max: 361\r\n\r\n\r\nrapdev1@rapdev1:/data/proj/sdk/tb3_ws$ ros2 launch turtlebot3_bringup robot.launch.py\r\nurdf_file_name : turtlebot3_waffle.urdf\r\n[INFO] [launch]: process[robot_state_publisher-1]: started with pid [27970]\r\n[INFO] [launch]: process[turtlebot3_ros-2]: started with pid [27971]\r\nInitialize urdf model from file: /data/proj/sdk/tb3_ws/install/turtlebot3_description/share/turtlebot3_description/urdf/turtlebot3_waffle.urdf\r\nParsing robot urdf xml string.\r\nLink base_link had 7 children\r\nLink camera_link had 2 children\r\nLink camera_depth_frame had 1 children\r\nLink camera_depth_optical_frame had 0 children\r\nLink camera_rgb_frame had 1 children\r\nLink camera_rgb_optical_frame had 0 children\r\nLink caster_back_left_link had 0 children\r\nLink caster_back_right_link had 0 children\r\nLink imu_link had 0 children\r\nLink base_scan had 0 children\r\nLink wheel_left_link had 0 children\r\nLink wheel_right_link had 0 children\r\ngot segment base_footprint\r\ngot segment base_link\r\ngot segment base_scan\r\ngot segment camera_depth_frame\r\ngot segment camera_depth_optical_frame\r\ngot segment camera_link\r\ngot segment camera_rgb_frame\r\ngot segment camera_rgb_optical_frame\r\ngot segment caster_back_left_link\r\ngot segment caster_back_right_link\r\ngot segment imu_link\r\ngot segment wheel_left_link\r\ngot segment wheel_right_link\r\n[INFO] [turtlebot3_node]: Init TurtleBot3 Node Main\r\nAdding fixed segment from base_footprint to base_link\r\nAdding fixed segment from base_link to camera_link\r\nAdding fixed segment from camera_link to camera_depth_frame\r\nAdding fixed segment from camera_depth_frame to camera_depth_optical_frame\r\nAdding fixed segment from camera_link to camera_rgb_frame\r\nAdding fixed segment from camera_rgb_frame to camera_rgb_optical_frame\r\nAdding fixed segment from base_link to caster_back_left_link\r\nAdding fixed segment from base_link to caster_back_right_link\r\nAdding fixed segment from base_link to imu_link\r\nAdding fixed segment from base_link to base_scan\r\nAdding moving segment from base_link to wheel_left_link\r\nAdding moving segment from base_link to wheel_right_link\r\n\r\n\r\nrapdev1@rapdev1:/data/proj/sdk/tb3_ws$ ros2 topic list\r\n/imu\r\n/joint_states\r\n/odom\r\n/parameter_events\r\n/robot_description\r\n/rosout\r\n/scan\r\n/scan_half\r\n/sensor_state\r\n/tf\r\n/tf_static\r\n/time_sync\r\n\r\n"
  repo: 'https://api.github.com/repos/ROBOTIS-GIT/turtlebot3'
  labels:
    - bug
    - in progress
- url: 'https://github.com/ROBOTIS-GIT/turtlebot3/issues/388'
  title: >-
    Raspberry Pi Burger Rasbian image compile error : Could not find the
    required component 'interactive_markers'.
  body: "ISSUE TEMPLATE ver. 0.2.0\r\n\r\n1. Which TurtleBot3 you have?\r\n\r\n    - [x] Burger\r\n    - [ ] Waffle\r\n    - [ ] Waffle Pi\r\n\r\n2. Which SBC(Single Board Computer) is working on TurtleBot3?\r\n\r\n    - [x] Raspberry Pi 3\r\n    - [ ] Intel Joule 570x\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)\r\n\r\n3. Which OS you installed in SBC?\r\n\r\n    - [ ] Ubuntu MATE 16.04 or later\r\n    - [x] Raspbian\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)\r\n\r\n4. Which OS you installed in Remote PC?\r\n\r\n    - [x] Ubuntu 16.04 LTS (Xenial Xerus)\r\n    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)\r\n    - [ ] Linux Mint 18.x\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)\r\n\r\n\r\n7. Copy and Paste your error message on terminal\r\n\r\n    - when i use catkin_make command, I get this error message : \r\n\r\n\r\nCould not find the required component 'interactive_markers'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.\r\nCMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):\r\n  Could not find a package configuration file provided by\r\n  \"interactive_markers\" with any of the following names:\r\n\r\n    interactive_markersConfig.cmake\r\n    interactive_markers-config.cmake\r\n\r\n\r\n  \r\n8. Please, describe detailedly what difficulty you are in \r\n\r\n    -  I cannot install ros-kinetic-interactive-marker.  This raspberry pi image is downloaded from http://emanual.robotis.com/docs/en/platform/turtlebot3/raspberry_pi_3_setup/#install-linux-based-on-raspbian .... So this is not a ubuntu mate distribution. I guess provided Linux distro image based on Raspbian has a compiled version of ros. so we cannot install interactive-marker.\r\n\r\nsudo apt-get install ros-kinetic-interactive-marker\r\nReading package lists... Done\r\nBuilding dependency tree\r\nReading state information... Done\r\nE: Unable to locate package ros-kinetic-interactive-marker\r\n\r\nhow can i solve this catkin_make compile error problem.. ?? we cannot install package by using apt install ros-kinetic-*"
  repo: 'https://api.github.com/repos/ROBOTIS-GIT/turtlebot3'
  labels:
    - question
- url: 'https://github.com/ROBOTIS-GIT/turtlebot3/issues/385'
  title: turtlebot3 navigation & cartographer launch
  body: "ISSUE TEMPLATE ver. 0.2.0\r\n\r\n1. Which TurtleBot3 you have?\r\n\r\n    - [ O ] Burger\r\n    - [ ] Waffle\r\n    - [ ] Waffle Pi\r\n\r\n2. Which SBC(Single Board Computer) is working on TurtleBot3?\r\n\r\n    - [ O ] Raspberry Pi 3\r\n    - [ ] Intel Joule 570x\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)\r\n\r\n3. Which OS you installed in SBC?\r\n\r\n    - [ O ] Ubuntu MATE 16.04 or later\r\n    - [ ] Raspbian\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)\r\n\r\n4. Which OS you installed in Remote PC?\r\n\r\n    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)\r\n    - [ O ] Ubuntu 18.04 LTS (Bionic Beaver)\r\n    - [ ] Linux Mint 18.x\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)\r\n\r\n5. Write down software version and firmware version\r\n\r\n    - Software version: [x.x.x]\r\n    - Firmware version: [x.x.x]\r\n \r\n6. Write down the commands you used in order\r\n\r\n    - ros2 launch turtlebot3_cartographer cartographer.launch.py\r\n    - ros2 launch turtlebot3_navigation2 navigation2.launch.py\r\n\r\n \r\n7. Copy and Paste your error message on terminal\r\n\r\nros2 launch turtlebot3_cartographer cartographer.launch.py\r\n[ERROR] [launch.LaunchService]: Caught exception in launch (see debug for traceback): cannot import name 'DeclareLaunchArgument'\r\n\r\nros2 launch turtlebot3_navigation2 navigation2.launch.py\r\n[ERROR] [launch.LaunchService]: Caught exception in launch (see debug for traceback): \"package 'nav2_bringup' not found, searching: ['/opt/ros/bouncy', '/home/song/turtlebot3_ws/install/turtlebot3', '/home/song/turtlebot3_ws/install/turtlebot3_teleop', '/home/song/turtlebot3_ws/install/turtlebot3_node', '/home/song/turtlebot3_ws/install/turtlebot3_navigation2', '/home/song/turtlebot3_ws2/install/turtlebot3_navigation2', '/home/song/turtlebot3_ws/install/turtlebot3_msgs', '/home/song/turtlebot3_ws/install/turtlebot3_bringup', '/home/song/turtlebot3_ws/install/turtlebot3_description', '/home/song/turtlebot3_ws/install/turtlebot3_cartographer', '/home/song/turtlebot3_ws/install/pcl_conversions', '/home/song/ros2_ws/install/rviz_assimp_vendor', '/home/song/ros2_ws/install/ros_environment', '/home/song/ros2_ws/install/launch', '/home/song/ros2_ws/install/osrf_pycommon', '/home/song/ros2_ws/install/libyaml_vendor', '/home/song/ros2_ws/install/libcurl_vendor', '/home/song/ros2_ws/install/ament_cmake_gmock', '/home/song/ros2_ws/install/ament_cmake_gtest', '/home/song/ros2_ws/install/console_bridge_vendor', '/home/song/ros2_ws/install/ament_xmllint', '/home/song/ros2_ws/install/ament_pyflakes', '/home/song/ros2_ws/install/ament_pep8', '/home/song/ros2_ws/install/ament_pep257', '/home/song/ros2_ws/install/ament_lint_auto', '/home/song/ros2_ws/install/ament_cmake_pytest', '/home/song/ros2_ws/install/ament_cmake_nose', '/home/song/ros2_ws/install/ament_cmake_auto', '/home/song/ros2_ws/install/ament_cmake', '/home/song/ros2_ws/install/ament_cmake_test', '/home/song/ros2_ws/install/ament_cmake_target_dependencies', '/home/song/ros2_ws/install/ament_cmake_python', '/home/song/ros2_ws/install/ament_cmake_export_dependencies', '/home/song/ros2_ws/install/ament_cmake_libraries', '/home/song/ros2_ws/install/ament_cmake_include_directories', '/home/song/ros2_ws/install/ament_cmake_export_link_flags', '/home/song/ros2_ws/install/ament_cmake_export_interfaces', '/home/song/ros2_ws/install/ament_cmake_export_libraries', '/home/song/ros2_ws/install/ament_cmake_export_include_directories', '/home/song/ros2_ws/install/ament_cmake_export_definitions', '/home/song/ros2_ws/install/ament_cmake_core', '/home/song/ros2_ws/install/ament_package', '/home/song/ros2_ws/install/ament_lint_cmake', '/home/song/ros2_ws/install/ament_index_python', '/home/song/ros2_ws/install/ament_flake8', '/home/song/ros2_ws/install/ament_cpplint', '/home/song/ros2_ws/install/ament_cppcheck', '/home/song/ros2_ws/install/ament_copyright']\r\n\r\n8. Please, describe detailedly what difficulty you are in \r\n\r\n    - I followed the instruction of turtlebot3 ros2 and it can worked until bringup and teleop and rviz.\r\n      When launching turtlebot3 navigation & turtlebot3 cartographer, it came up like above.\r\n      Firstly, I could not find what is related with \"DeclareLaunchArgument\" which written in turtlebot3 navigation.\r\n     Secondly, is the file of \"nav2_bringup\" only limited in ros2 crystal version (Currently installed ros2 bouncy for RemotePC) ?  \r\n\r\n    Thank you\r\n"
  repo: 'https://api.github.com/repos/ROBOTIS-GIT/turtlebot3'
  labels:
    - in progress
    - question
- url: 'https://github.com/ROBOTIS-GIT/turtlebot3/issues/376'
  title: '[melodic] Robot model not visible on Rviz using fake node '
  body: "ISSUE TEMPLATE ver. 0.2.0\r\n\r\n1. Which TurtleBot3 you have?\r\n    - [x] I'm Trying to simulate them.\r\n    - [x] Burger\r\n    - [x] Waffle\r\n    - [x] Waffle Pi\r\n\r\n2. Which SBC(Single Board Computer) is working on TurtleBot3?\r\n    - [x] None cf: 1\r\n    - [ ] Raspberry Pi 3\r\n    - [ ] Intel Joule 570x\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)\r\n\r\n3. Which OS you installed in SBC?\r\n    - [x] None cf: 1\r\n    - [ ] Ubuntu MATE 16.04 or later\r\n    - [ ] Raspbian\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)\r\n\r\n4. Which OS you installed in Remote PC?\r\n\r\n    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)\r\n    - [x] Ubuntu 18.04 LTS (Bionic Beaver)\r\n    - [ ] Linux Mint 18.x\r\n    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)\r\n\r\n5. Write down software version and firmware version\r\n\r\n    - Software version: [1.14.3]  (melodic)\r\n    - Firmware version: [x.x.x]\r\n\r\n6. Write down the commands you used in order\r\n### To install for melodic from sources\r\n\r\nI'm using this script :\r\n```\r\nmkdir -p ~/catkin_ws/src/\r\ncd ~/catkin_ws/src/\r\ngit clone https://github.com/ROBOTIS-GIT/turtlebot3.git --branch melodic-devel\r\ngit clone https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git --branch melodic-devel\r\ngit clone https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git --branch melodic-devel\r\ngit clone https://github.com/ROBOTIS-GIT/turtlebot3_applications_msgs.git --branch melodic-devel\r\ngit clone https://github.com/ROBOTIS-GIT/turtlebot3_applications.git\r\ngit clone https://github.com/ROBOTIS-GIT/turtlebot3_autorace.git\r\ngit clone https://github.com/ROBOTIS-GIT/turtlebot3_deliver.git\r\ncd ~/catkin_ws/\r\n\r\nsudo apt install ros-melodic-joy ros-melodic-teleop-twist-joy \\\r\n                 ros-melodic-teleop-twist-keyboard ros-melodic-laser-proc \\\r\n                 ros-melodic-rgbd-launch ros-melodic-depthimage-to-laserscan \\\r\n                 ros-melodic-rosserial-arduino ros-melodic-rosserial-python \\\r\n                 ros-melodic-rosserial-server ros-melodic-rosserial-client \\\r\n                 ros-melodic-rosserial-msgs ros-melodic-amcl \\\r\n                 ros-melodic-map-server ros-melodic-move-base \\\r\n                 ros-melodic-urdf ros-melodic-xacro \\\r\n                 ros-melodic-compressed-image-transport \\\r\n                 ros-melodic-rqt-image-view ros-melodic-gmapping \\\r\n                 ros-melodic-navigation ros-melodic-interactive-markers\r\n# Result :\r\n# E: Unable to locate package ros-melodic-teleop-twist-joy\r\n# E: Unable to locate package ros-melodic-depthimage-to-laserscan\r\n# E: Unable to locate package ros-melodic-gmapping\r\n\r\nrosdep install --from-paths src --ignore-src -r -y\r\n# Result :\r\n# ERROR: the following packages/stacks could not have their rosdep keys resolved\r\n# to system dependencies:\r\n# turtlebot3_slam: Cannot locate rosdep definition for [gmapping]\r\n# Continuing to install resolvable dependencies...\r\n# All required rosdeps installed successfully\r\n\r\n# Intall cartographer from ros binaries\r\nsudo apt install ros-melodic-cartographer ros-melodic-cartographer-ros ros-melodic-cartographer-ros-msgs ros-melodic-cartographer-rviz\r\ncatkin_make\r\n\r\n```\r\nnot found packages :\r\n - Gmapping => i'm planning to use cartographer anyway.\r\n - ros-melodic-teleop-twist-joy => i'm not planning to control it with joystick.\r\n - ros-melodic-depthimage-to-laserscan => I'm planning to use burger\r\n\r\n ### tests :\r\n #### Fake node\r\n I'm trying to simulate with fake node according to :\r\n http://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/#turtlebot3-simulation-using-fake-node\r\n\r\n ##### Burger\r\n Terminal 1 :\r\n ```\r\n export TURTLEBOT3_MODEL=burger\r\n roslaunch turtlebot3_fake turtlebot3_fake.launch\r\n ```\r\n Terminal 2 :\r\n ```\r\n export TURTLEBOT3_MODEL=burger\r\n roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch\r\n ```\r\n\r\n**Results**\r\nThe robot model is not visible, but i can teleop the robot\r\n![rviz](https://user-images.githubusercontent.com/6124823/51401805-0103c700-1b4c-11e9-9f6a-b405825ecdfc.png)\r\n  ##### Waffle\r\n Terminal 1 :\r\n ```\r\n export TURTLEBOT3_MODEL=waffle\r\n roslaunch turtlebot3_fake turtlebot3_fake.launch\r\n ```\r\n Terminal 2 :\r\n ```\r\n export TURTLEBOT3_MODEL=waffle\r\n roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch\r\n ```\r\n\r\n**Results**\r\nThe model is... definitively not the expected one ;). And I can't teleop it. \r\n![waffle_rviz](https://user-images.githubusercontent.com/6124823/51401781-f9dcb900-1b4b-11e9-876e-18d079d8648e.png)\r\n\r\n#### Gazebo\r\nTerminal 1 :\r\n```\r\nexport TURTLEBOT3_MODEL=burger\r\nroslaunch turtlebot3_gazebo turtlebot3_empty_world.launch\r\n```\r\n\r\n7. Copy and Paste your error message on terminal\r\n\r\n```\r\nvirgile@Leon:~/catkin_ws$ roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch\r\n... logging to /home/virgile/.ros/log/b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f/roslaunch-Leon-29954.log\r\nChecking log directory for disk usage. This may take awhile.\r\nPress Ctrl-C to interrupt\r\nDone checking log file disk usage. Usage is <1GB.\r\n\r\nxacro: in-order processing became default in ROS Melodic. You can drop the option.\r\nstarted roslaunch server http://Leon:35913/\r\n\r\nSUMMARY\r\n========\r\n\r\nPARAMETERS\r\n * /gazebo/enable_ros_network: True\r\n * /robot_description: <?xml version=\"1....\r\n * /rosdistro: melodic\r\n * /rosversion: 1.14.3\r\n * /use_sim_time: True\r\n\r\nNODES\r\n  /\r\n    gazebo (gazebo_ros/gzserver)\r\n    gazebo_gui (gazebo_ros/gzclient)\r\n    spawn_urdf (gazebo_ros/spawn_model)\r\n\r\nauto-starting new master\r\nprocess[master]: started with pid [29967]\r\nROS_MASTER_URI=http://localhost:11311\r\n\r\nsetting /run_id to b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f\r\nprocess[rosout-1]: started with pid [29978]\r\nstarted core service [/rosout]\r\nprocess[gazebo-2]: started with pid [29984]\r\nprocess[gazebo_gui-3]: started with pid [29989]\r\nprocess[spawn_urdf-4]: started with pid [29995]\r\n[ INFO] [1547830461.817209739]: Finished loading Gazebo ROS API Plugin.\r\n[ INFO] [1547830461.824400081]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...\r\n[ INFO] [1547830461.853749754]: Finished loading Gazebo ROS API Plugin.\r\n[ INFO] [1547830461.865668517]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...\r\nTraceback (most recent call last):\r\n  File \"/opt/ros/melodic/lib/gazebo_ros/spawn_model\", line 31, in <module>\r\n    from tf.transformations import quaternion_from_euler\r\n  File \"/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py\", line 31, in <module>\r\n    from .listener import Transformer, TransformListener, TransformerROS\r\n  File \"/opt/ros/melodic/lib/python2.7/dist-packages/tf/listener.py\", line 29, in <module>\r\n    import numpy\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/__init__.py\", line 142, in <module>\r\n    from . import core\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/core/__init__.py\", line 59, in <module>\r\n    from . import numeric\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/core/numeric.py\", line 3093, in <module>\r\n    from . import fromnumeric\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py\", line 17, in <module>\r\n    from . import _methods\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/core/_methods.py\", line 158, in <module>\r\n    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__\r\nAttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'\r\nWarning [parser.cc:950] XML Element[scene], child of element[sdf] not defined in SDF. Ignoring[scene]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.\r\n[spawn_urdf-4] process has died [pid 29995, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -model turtlebot3_burger -x 0.0 -y 0.0 -z 0.0 -param robot_description __name:=spawn_urdf __log:=/home/virgile/.ros/log/b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f/spawn_urdf-4.log].\r\nlog file: /home/virgile/.ros/log/b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f/spawn_urdf-4*.log\r\n[ INFO] [1547830462.483451793, 0.023000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.\r\n[ INFO] [1547830462.530468309, 0.065000000]: Physics dynamic reconfigure ready.\r\n```\r\n\r\n8. Please, describe detailedly what difficulty you are in\r\n\r\n    - The problem seems to be linked somehow with the model of the robot. as stated in :\r\n\r\n```\r\n[spawn_urdf-4] process has died [pid 29995, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -model turtlebot3_burger -x 0.0 -y 0.0 -z 0.0 -param robot_description __name:=spawn_urdf __log:=/home/virgile/.ros/log/b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f/spawn_urdf-4.log].\r\n```\r\n\r\n  - Another clue is a problem in the SDF file but it should **only concern Gazebo** right ?\r\n```\r\nWarning [parser.cc:950] XML Element[scene], child of element[sdf] not defined in SDF. Ignoring[scene]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.\r\n```\r\n\r\n  - There may be a problem in one model is causing the following error of quaternion conversion. Quaternions must be normed, if not that can create conversions error. A not defined quaternion aka (0,0,0,0) can lead to the following error ?\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/opt/ros/melodic/lib/gazebo_ros/spawn_model\", line 31, in <module>\r\n    from tf.transformations import quaternion_from_euler\r\n  File \"/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py\", line 31, in <module>\r\n    from .listener import Transformer, TransformListener, TransformerROS\r\n  File \"/opt/ros/melodic/lib/python2.7/dist-packages/tf/listener.py\", line 29, in <module>\r\n    import numpy\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/__init__.py\", line 142, in <module>\r\n    from . import core\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/core/__init__.py\", line 59, in <module>\r\n    from . import numeric\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/core/numeric.py\", line 3093, in <module>\r\n    from . import fromnumeric\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py\", line 17, in <module>\r\n    from . import _methods\r\n  File \"/home/virgile/.local/lib/python2.7/site-packages/numpy/core/_methods.py\", line 158, in <module>\r\n    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__\r\nAttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'\r\n```\r\n\r\nThanks for your help and beautiful work :)\r\n"
  repo: 'https://api.github.com/repos/ROBOTIS-GIT/turtlebot3'
  labels:
    - question
- url: 'https://github.com/ROBOTIS-GIT/turtlebot3/issues/340'
  title: Turtlebot3_core doesn't grab the NAMESPACE configuration
  body: "Hello, I'm working with multiple **turtlebot3**.\r\n\r\n1. Which TurtleBot3 you have?\r\n\r\n    - Burger\r\n  \r\n2. Which SBC(Single Board Computer) is working on TurtleBot3?\r\n\r\n    - Raspberry Pi 3\r\n  \r\n3. Which OS you installed in SBC?\r\n\r\n    - Ubuntu MATE 16.04 or later\r\n   \r\n4. Which OS you installed in Remote PC?\r\n\r\n    - Ubuntu 16.04 LTS (Xenial Xerus)\r\n\r\n5. Write down software version and firmware version\r\n\r\n    - Software version: [1.12.14]\r\n    - Firmware version: [1.2.3]\r\n\r\n**turtlebot3_robot.launch**\r\n```\r\n<launch>\r\n  <arg name=\"multi_robot_name\" default=\"\"/>\r\n  <arg name=\"set_lidar_frame_id\" default=\"base_scan\"/>\r\n\r\n  <include file=\"$(find turtlebot3_bringup)/launch/turtlebot3_core.launch\">\r\n    <arg name=\"multi_robot_name\" value=\"$(arg multi_robot_name)\"/>\r\n  </include>\r\n  <include file=\"$(find turtlebot3_bringup)/launch/turtlebot3_lidar.launch\">\r\n    <arg name=\"set_frame_id\" value=\"$(arg set_lidar_frame_id)\"/>\r\n  </include>\r\n\r\n  <node pkg=\"turtlebot3_bringup\" type=\"turtlebot3_diagnostics\" name=\"turtlebot3_diagnostics\" output=\"screen\"/>\r\n</launch>\r\n```\r\n\r\nwhich launches: **turtlebot3_core.launch**\r\n```\r\n<launch>\r\n  <arg name=\"multi_robot_name\" default=\"\"/>\r\n\r\n  <node pkg=\"rosserial_python\" type=\"serial_node.py\" name=\"turtlebot3_core\" output=\"screen\">\r\n    <param name=\"port\" value=\"/dev/ttyACM0\"/>\r\n    <param name=\"baud\" value=\"115200\"/>\r\n    <param name=\"tf_prefix\" value=\"$(arg multi_robot_name)\"/>\r\n  </node>\r\n</launch>\r\n```\r\nThe former is being run using this params:\r\n`ROS_NAMESPACE=tb3_1 roslaunch turtlebot3_bringup turtlebot3_robot.launch multi_robot_name:=\"tb3_1\" set_lidar_frame_id:=\"tb3_1/base_scan\"`\r\n\r\nbut the TF tree doesn't successfully grab the namespace configuration for the `odom` and `base_footprint`: [TF Tree here](https://imgur.com/a/RG4MiWe)\r\n\r\nI'm getting this warning on the console when launching (not sure if it has relation or not): [Here](https://imgur.com/a/uYud34B)\r\n\r\nI've gone through the source code for both the `serial_node.py` and `SerialClient.py`, and effectively there's no room in the code to grab the namespace for the frames (`odom` & `base_footprint`), I've added the simple fix for the former source file:\r\n`tf_prefix = rospy.get_param('~tf_prefix','')  #line 53`\r\n`client = SerialClient(port_name, baud, tf_prefix=tf_prefix, fix_pyserial_for_test=fix_pyserial_for_test) #line 90`\r\n\r\nbut for the `SerialClient.py` the patching becomes a bit tricky (posted the same issue at the rosserial_python git but seems like it's not actively maintained, so hope over here I'd get some support)\r\n\r\n```\r\ndef __init__(self, port=None, baud=57600, tf_prefix=None, timeout=5.0, fix_pyserial_for_test=False): #line 324\r\n# fix for grabbing namespace configurations (line 336)\r\n        if tf_prefix== None:\r\n            # namespace was not initialized\r\n            pass\r\n        else:\r\n            # setting the argument var to class var\r\n            self.tf_prefix=tf_prefix\r\n```\r\n(this was the easy part)\r\n\r\nafter these come `setupPublisher(self, data):` & `setupSubscriber(self, data):`, and here becomes tricky, I've been spending the last couple of hours working the code, but the debugging gets a bit complex since we're working directly over the robot and the battery runs out very fast. So that's the reason I dare to ask for help from you guys.\r\n\r\n(Read the two previous closed issues about this, however, it seems like the fix in the firmware wasn't yet added to the mainstream??)\r\n\r\nIs it my guess that the problem can be fixed by changing this code correct? please advice otherwise.\r\n\r\nThanks\r\n"
  repo: 'https://api.github.com/repos/ROBOTIS-GIT/turtlebot3'
  labels:
    - bug
    - question
